# setting directories

set_property(GLOBAL PROPERTY LIBDIR ${PROJECT_SOURCE_DIR}/libs)
set_property(GLOBAL PROPERTY RESDIR ${PROJECT_SOURCE_DIR}/res)
set_property(GLOBAL PROPERTY APPDIR ${PROJECT_SOURCE_DIR}/app)
set_property(GLOBAL PROPERTY ROOTDIR ${PROJECT_SOURCE_DIR})
